// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtxikTn91rfdjv1bH_9j0O4AEGqlCaCJI',
    appId: '1:811102471491:web:43772503a26ede26771bf6',
    messagingSenderId: '811102471491',
    projectId: 'pc-ishrat-farah',
    authDomain: 'pc-ishrat-farah.firebaseapp.com',
    storageBucket: 'pc-ishrat-farah.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn70MRRN2S1_WUQszC3frQOHTUiSMG_4Y',
    appId: '1:811102471491:android:3fff580b6aae746c771bf6',
    messagingSenderId: '811102471491',
    projectId: 'pc-ishrat-farah',
    storageBucket: 'pc-ishrat-farah.appspot.com',
  );
}
